spring:
  application:
    name: fare
  sleuth:
    sampler:
      probability: 100
  zipkin:
      baseUrl: http://localhost:9411

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: "*"