server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:h2:mem:flightSchedule
    platform: h2
    username: username
    password: "{cipher}58cb196e92a4890c65664e8c7da1f288e2830079b4451898f299c73ac67bb4d2"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false
  h2:
    console:
      enabled: true
      path: /h2-console


airline:
  disabled: