server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:h2:mem:flight-schedule
    platform: h2
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  h2:
    console:
      enabled: true
      path: /h2-console


airline:
  disabled: