spring:
  application:
    name: currency
  sleuth:
    sampler:
      probability: 100
  zipkin:
      baseUrl: http://localhost:9411

server:
  port: 8085

converter:
  url: https://api.exchangeratesapi.io/latest?base=%s&symbols=%s

management:
  endpoints:
    web:
      exposure:
        include: "*"