spring:
  application:
    name: currency
server:
  port: 8085

converter:
  url: https://api.exchangeratesapi.io/latest?base=%s&symbols=%s

zuul:
  routes:
    currency: "/cc/**"
  ignored-services: currency

management:
  endpoints:
    web:
      exposure:
        include: "*"