spring:
  application:
    name: gateway
  sleuth:
    sampler:
      probability: 100
  zipkin:
    baseUrl: http://localhost:9411

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  routes:
    currency: "/cc/**"
  ignored-services: currency
